language: python
python: 3.9
node_js:
- '6'

before_install:
- export TZ=America/Bogota
- nvm install 6
- node --version
- nvm --version

install:
- npm install
- pip install -r requirements.txt

branches:
  only:
    - master

script: "lektor build"

deploy:
  provider: script
  script: "lektor deploy ghpages-https"
  on:
    branch: master

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
    - webpack/node_modules
